'use strict';

/**
 * Initialize default options.
 */

module.exports = function options_(app) {
  app.option({
    toc: {append: '\n\n_(Table of contents generated by [update])_'}
  });
  app.option('view engine', 'md');
  app.disable('default routes');
  app.option('layoutDelims', ['{%', '%}']);
  app.option('escapeDelims', ['<%%', '<%']);
};
