'use strict';

/**
 * Define default options.
 */

module.exports = function options_(app) {
  app.option({
    toc: {append: '\n\n_(Table of contents generated by [update])_'}
  });

  // engines
  app.option('view engine', 'md');

  // delimiters
  app.option('layoutDelims', ['{%', '%}']);
  app.option('escapeDelims', {
    from: ['<%%', '%>'],
    to: ['<%', '%>']
  });
};
