#!/bin/zsh

# Borrowed from grunt-cli, by way of gulp
# http://gruntjs.com/
#
# Copyright (c) 2012 Tyler Kellen, contributors
# Licensed under the MIT license.
# https://github.com/gruntjs/grunt/blob/master/LICENSE-MIT

# Usage:
#
# To enable zsh <tab> completion for update, add the following line (minus the
# leading #, which is the zsh comment character) to your ~/.zshrc file:
#
# eval "$(update --completion=zsh)"

# Enable zsh autocompletion.
function _update_completion() {
  # Grab tasks
  compls=$(update --tasks-simple)
  completions=(${=compls})
  compadd -- $completions
}

compdef _update_completion update
